# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c16.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fo16_pb2 as fo16__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tc16.proto\x12\x14\x62rucon.configuration\x1a\nfo16.proto\"\xd7\x02\n\x08Position\x12m\n\nx_position\x18\x01 \x01(\x01\x42Y\x82\xa6\x1dPX-axis forward, y-axis starboard and z-axis down. (0,0,0) is at midship and keel\x8a\xa6\x1d\x01m\x12m\n\ny_position\x18\x02 \x01(\x01\x42Y\x82\xa6\x1dPX-axis forward, y-axis starboard and z-axis down. (0,0,0) is at midship and keel\x8a\xa6\x1d\x01m\x12m\n\nz_position\x18\x03 \x01(\x01\x42Y\x82\xa6\x1dPX-axis forward, y-axis starboard and z-axis down. (0,0,0) is at midship and keel\x8a\xa6\x1d\x01m\"h\n\x0fSerialInterface\x12\x17\n\x0f\x63ontroller_name\x18\x01 \x01(\t\x12\x16\n\x0e\x63om_port_index\x18\x02 \x01(\x05\x12\x10\n\x08udp_port\x18\x03 \x01(\x05\x12\x12\n\nip_address\x18\x04 \x01(\t\"H\n\x11\x45thernetInterface\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x11\n\tinterface\x18\x03 \x01(\t*;\n\x08LedColor\x12\x0f\n\x0bUnspecified\x10\x00\x12\t\n\x05Green\x10\x01\x12\n\n\x06Orange\x10\x02\x12\x07\n\x03Red\x10\x03*\xb9\x03\n\x08UnitType\x12\x18\n\x14UnitType_Unspecified\x10\x00\x12\x14\n\x10UnitType_Percent\x10\x01\x12\x10\n\x0cUnitType_RPM\x10\x02\x12\x14\n\x10UnitType_Degrees\x10\x03\x12\x14\n\x10UnitType_Seconds\x10\x0b\x12\x12\n\x0eUnitType_Hertz\x10\x0c\x12\x14\n\x10UnitType_Celsius\x10\r\x12\x10\n\x0cUnitType_Bar\x10\x0e\x12\x17\n\x13UnitType_MilliMeter\x10\x15\x12\x17\n\x13UnitType_CentiMeter\x10\x16\x12\x12\n\x0eUnitType_Meter\x10\x17\x12\x19\n\x15UnitType_MeterSquared\x10\x18\x12\x1c\n\x18UnitType_MetersPerSecond\x10\x1f\x12\x12\n\x0eUnitType_Knots\x10 \x12\x11\n\rUnitType_Volt\x10)\x12\x18\n\x14UnitType_MilliAmpere\x10*\x12\x13\n\x0fUnitType_Ampere\x10+\x12\x15\n\x11UnitType_KiloWatt\x10,\x12\x17\n\x13UnitType_KiloNewton\x10-b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c16_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSITION'].fields_by_name['x_position']._options = None
  _globals['_POSITION'].fields_by_name['x_position']._serialized_options = b'\202\246\035PX-axis forward, y-axis starboard and z-axis down. (0,0,0) is at midship and keel\212\246\035\001m'
  _globals['_POSITION'].fields_by_name['y_position']._options = None
  _globals['_POSITION'].fields_by_name['y_position']._serialized_options = b'\202\246\035PX-axis forward, y-axis starboard and z-axis down. (0,0,0) is at midship and keel\212\246\035\001m'
  _globals['_POSITION'].fields_by_name['z_position']._options = None
  _globals['_POSITION'].fields_by_name['z_position']._serialized_options = b'\202\246\035PX-axis forward, y-axis starboard and z-axis down. (0,0,0) is at midship and keel\212\246\035\001m'
  _globals['_LEDCOLOR']._serialized_start=573
  _globals['_LEDCOLOR']._serialized_end=632
  _globals['_UNITTYPE']._serialized_start=635
  _globals['_UNITTYPE']._serialized_end=1076
  _globals['_POSITION']._serialized_start=48
  _globals['_POSITION']._serialized_end=391
  _globals['_SERIALINTERFACE']._serialized_start=393
  _globals['_SERIALINTERFACE']._serialized_end=497
  _globals['_ETHERNETINTERFACE']._serialized_start=499
  _globals['_ETHERNETINTERFACE']._serialized_end=571
# @@protoc_insertion_point(module_scope)
