# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fo16.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfo16.proto\x1a google/protobuf/descriptor.proto:4\n\x0b\x44\x65scription\x12\x1d.google.protobuf.FieldOptions\x18\xe0\xd4\x03 \x01(\t:-\n\x04Unit\x12\x1d.google.protobuf.FieldOptions\x18\xe1\xd4\x03 \x01(\t:0\n\x07\x44\x65\x66\x61ult\x12\x1d.google.protobuf.FieldOptions\x18\xe2\xd4\x03 \x01(\x01:,\n\x03Min\x12\x1d.google.protobuf.FieldOptions\x18\xea\xd4\x03 \x01(\x01:,\n\x03Max\x12\x1d.google.protobuf.FieldOptions\x18\xeb\xd4\x03 \x01(\x01:.\n\x05Scale\x12\x1d.google.protobuf.FieldOptions\x18\xec\xd4\x03 \x01(\x01:+\n\x02\x44p\x12\x1d.google.protobuf.FieldOptions\x18\xf4\xd4\x03 \x01(\x08:4\n\x0b\x41\x63\x63\x65ssLevel\x12\x1d.google.protobuf.FieldOptions\x18\xfe\xd4\x03 \x01(\x05:-\n\x04Size\x12\x1d.google.protobuf.FieldOptions\x18\x88\xd5\x03 \x01(\x05:2\n\tDimension\x12\x1d.google.protobuf.FieldOptions\x18\x92\xd5\x03 \x01(\x05:>\n\x11MaxExtensionIndex\x12!.google.protobuf.EnumValueOptions\x18\xf0\xa2\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fo16_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
